### ISSUE TITLE
di package.json sini ini

### ISSUE THREAD

**Issue by Yuri-Neko** [Nayla-Hnf27/My-api#2]
{
  "name": "nodejs",
  "version": "1.0.0",
  "description": "Contoh proyek Node.js",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.6.8",
    "cors": "^2.8.5",
    "express": "^4.19.2",
    "node-fetch": "^2.6.7"
  }
}

**Comment by Nayla-Hnf27** [comment]
Hmm
